import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import {
  attachScrollSequence,
  HINGE,
  hingeStyle,
  SEQ_PLAIN,
  SEQ_WELD,
  weldClockActive,
} from './useAboutHinge';

/**
 * Golden values in this file were generated by re-running the OLD site.js
 * arithmetic (assets/site.js:4244-4278 and 4421-4439) verbatim in node and
 * printing the result. They are not hand-derived, and they are not rounded —
 * if one of them changes, the port has drifted from the source.
 */

/* ------------------------------------------------------------ helpers -- */

let host: HTMLDivElement;
let tiles: HTMLElement[];
let detach: () => void = () => {};

/** Every rAF the engine schedules, so a test can step frames by hand. */
let rafQueue: FrameRequestCallback[];
let rafCancelled: number[];

/** The IntersectionObserver the engine constructs, exposed to the test. */
interface FakeIO {
  cb: IntersectionObserverCallback;
  init: IntersectionObserverInit | undefined;
  observed: Element[];
  disconnected: boolean;
}
let ios: FakeIO[];

function setTop(px: number) {
  host.getBoundingClientRect = () => ({ top: px }) as DOMRect;
}

/** Drain exactly one queued frame. */
function frame() {
  const q = rafQueue;
  rafQueue = [];
  q.forEach((fn) => fn(0));
}

function fire(isIntersecting: boolean) {
  const io = ios[ios.length - 1];
  io.cb(
    [{ isIntersecting } as IntersectionObserverEntry],
    io as unknown as IntersectionObserver,
  );
}

beforeEach(() => {
  rafQueue = [];
  rafCancelled = [];
  ios = [];

  host = document.createElement('div');
  host.id = 'aboutCollage';
  tiles = Array.from({ length: 6 }, () => {
    const f = document.createElement('figure');
    f.className = 'ac-tile';
    host.appendChild(f);
    return f;
  });
  document.body.appendChild(host);

  window.innerHeight = 1000;
  setTop(0);

  /* Reset to "nothing matches" — several tests below REPLACE window.matchMedia
     outright (assignment, not a spy), and vi.restoreAllMocks cannot undo that.
     Without this, one reduced-motion test poisons every later one. */
  window.matchMedia = ((q: string) =>
    ({
      matches: false,
      media: q,
      addEventListener: () => {},
      removeEventListener: () => {},
    }) as unknown as MediaQueryList) as typeof window.matchMedia;

  let id = 0;
  vi.stubGlobal('requestAnimationFrame', (fn: FrameRequestCallback) => {
    rafQueue.push(fn);
    return ++id;
  });
  vi.stubGlobal('cancelAnimationFrame', (n: number) => {
    rafCancelled.push(n);
  });
  vi.stubGlobal(
    'IntersectionObserver',
    class {
      cb: IntersectionObserverCallback;
      init: IntersectionObserverInit | undefined;
      observed: Element[] = [];
      disconnected = false;
      constructor(cb: IntersectionObserverCallback, init?: IntersectionObserverInit) {
        this.cb = cb;
        this.init = init;
        ios.push(this as unknown as FakeIO);
      }
      observe(el: Element) {
        this.observed.push(el);
      }
      unobserve() {}
      disconnect() {
        this.disconnected = true;
      }
      takeRecords() {
        return [];
      }
    },
  );
});

afterEach(() => {
  detach();
  detach = () => {};
  host.remove();
  document.getElementById('process')?.remove();
  vi.unstubAllGlobals();
  vi.restoreAllMocks();
});

/* ------------------------------------------------------- the hinge table -- */

describe('HINGE', () => {
  it('is the source table, tile for tile (site.js:4421-4428)', () => {
    expect(HINGE).toEqual([
      { ax: 'X', deg: -84, org: '50% 0%' },
      { ax: 'Y', deg: -78, org: '100% 50%' },
      { ax: 'Y', deg: 78, org: '0% 50%' },
      { ax: 'X', deg: -84, org: '50% 0%' },
      { ax: 'Y', deg: 78, org: '0% 50%' },
      { ax: 'Y', deg: -78, org: '100% 50%' },
    ]);
  });

  it('gives the two full-width tiles an X hinge and the four side tiles a Y', () => {
    // ac-w1 (the brand plate) and ac-w4 (the island shot) are the left column.
    expect(HINGE.map((h) => h.ax).join('')).toBe('XYYXYY');
  });

  it('swings X 84 degrees and Y 78 — the asymmetry is the source’s', () => {
    expect(new Set(HINGE.filter((h) => h.ax === 'X').map((h) => Math.abs(h.deg)))).toEqual(
      new Set([84]),
    );
    expect(new Set(HINGE.filter((h) => h.ax === 'Y').map((h) => Math.abs(h.deg)))).toEqual(
      new Set([78]),
    );
  });

  it('pairs every Y hinge sign with the edge it pivots on', () => {
    // Negative degrees pivot on the right edge, positive on the left.
    for (const h of HINGE) {
      if (h.ax !== 'Y') continue;
      expect(h.org).toBe(h.deg < 0 ? '100% 50%' : '0% 50%');
    }
  });
});

/* ------------------------------------------------------- the per-tile write -- */

describe('hingeStyle', () => {
  it('lands the fully-open pose at e=0', () => {
    expect(hingeStyle(0, 0)).toEqual({
      transform: 'translateZ(-70.0px) rotateX(-84.00deg)',
      opacity: '0.000',
    });
    expect(hingeStyle(0, 1)).toEqual({
      transform: 'translateZ(-70.0px) rotateY(-78.00deg)',
      opacity: '0.000',
    });
    expect(hingeStyle(0, 2)).toEqual({
      transform: 'translateZ(-70.0px) rotateY(78.00deg)',
      opacity: '0.000',
    });
  });

  it('halves depth and angle at e=0.5, and is already fully opaque there', () => {
    // opacity is min(1, e*2.1) — solid from e≈0.476 onward.
    expect(hingeStyle(0.5, 0)).toEqual({
      transform: 'translateZ(-35.0px) rotateX(-42.00deg)',
      opacity: '1.000',
    });
    expect(hingeStyle(0.5, 5)).toEqual({
      transform: 'translateZ(-35.0px) rotateY(-39.00deg)',
      opacity: '1.000',
    });
  });

  it('holds opacity to three decimals below the 1/2.1 knee', () => {
    expect(hingeStyle(0.25, 3)?.opacity).toBe('0.525');
    expect(hingeStyle(0.295_428_504_414_774_53, 2)?.opacity).toBe('0.620');
  });

  it('still WRITES at exactly e=0.999 — the guard is strictly greater', () => {
    expect(hingeStyle(0.999, 0)).toEqual({
      transform: 'translateZ(-0.1px) rotateX(-0.08deg)',
      opacity: '1.000',
    });
  });

  it('clears (returns null) the moment e passes 0.999', () => {
    expect(hingeStyle(0.9991, 0)).toBeNull();
    expect(hingeStyle(1, 0)).toBeNull();
  });

  it('wraps the table with i % 6, as the source does', () => {
    expect(hingeStyle(0.4, 6)).toEqual(hingeStyle(0.4, 0));
    expect(hingeStyle(0.4, 8)).toEqual(hingeStyle(0.4, 2));
  });
});

/* ------------------------------------------------------- the timing profiles -- */

describe('the two timing profiles', () => {
  it('is the free-scroll profile (site.js:4439)', () => {
    expect(SEQ_PLAIN).toEqual({
      start: 0.94,
      end: 0.2,
      span: 0.42,
      step: 0.112,
      scrub: 0.14,
    });
  });

  it('is the weld-door profile (site.js:4437-4438)', () => {
    expect(SEQ_WELD).toEqual({
      start: 1.21,
      end: 0.576,
      span: 0.42,
      step: 0.112,
      scrub: 0.26,
    });
  });

  it('shares span and step, and differs only in the run and the lerp', () => {
    expect(SEQ_WELD.span).toBe(SEQ_PLAIN.span);
    expect(SEQ_WELD.step).toBe(SEQ_PLAIN.step);
    expect(SEQ_WELD.scrub).toBeGreaterThan(SEQ_PLAIN.scrub);
    // The weld run starts BELOW the fold (>1) and ends past mid-viewport.
    expect(SEQ_WELD.start).toBeGreaterThan(1);
    expect(SEQ_WELD.end).toBeGreaterThan(0.5);
  });
});

describe('weldClockActive (site.js:4429-4431)', () => {
  const mq = (wide: boolean, calm: boolean) => {
    window.matchMedia = ((q: string) =>
      ({
        matches: q.includes('1121px') ? wide : q.includes('reduce') ? calm : false,
        media: q,
        addEventListener: () => {},
        removeEventListener: () => {},
      }) as unknown as MediaQueryList) as typeof window.matchMedia;
  };

  it('needs all three: desktop band, motion allowed, and #process on the page', () => {
    mq(true, false);
    expect(weldClockActive()).toBe(false); // no #process yet

    const p = document.createElement('div');
    p.id = 'process';
    document.body.appendChild(p);
    expect(weldClockActive()).toBe(true);

    mq(false, false);
    expect(weldClockActive()).toBe(false); // below 1121px

    mq(true, true);
    expect(weldClockActive()).toBe(false); // reduced motion
  });
});

/* ---------------------------------------------- the scrollSequence engine -- */

describe('attachScrollSequence', () => {
  it('does nothing without a host or without tiles', () => {
    const apply = vi.fn();
    attachScrollSequence(null, tiles, apply, SEQ_PLAIN)();
    attachScrollSequence(host, [], apply, SEQ_PLAIN)();
    expect(apply).not.toHaveBeenCalled();
    expect(ios).toHaveLength(0);
  });

  it('paints one frame IMMEDIATELY, before observing anything', () => {
    const apply = vi.fn();
    detach = attachScrollSequence(host, tiles, apply, SEQ_PLAIN);
    expect(apply).toHaveBeenCalledTimes(6);
    // and did not schedule — the first tick runs with live === false.
    expect(rafQueue).toHaveLength(0);
  });

  it('maps the collage rect top through START/END exactly (top=740, vh=1000)', () => {
    setTop(740);
    const seen: number[] = [];
    detach = attachScrollSequence(host, tiles, (_el, e) => seen.push(e), SEQ_PLAIN);
    // Golden: the old maths at t = (0.94 - 0.74) / 0.74.
    expect(seen[0]).toBeCloseTo(0.954_691_858_226_391, 12);
    expect(seen[1]).toBeCloseTo(0.758_002_266_262_667_8, 12);
    expect(seen[2]).toBeCloseTo(0.295_428_504_414_774_53, 12);
    // Tiles 3-5 have not started: the 0.112 stagger has not reached them.
    expect(seen.slice(3)).toEqual([0, 0, 0]);
  });

  it('writes the golden transforms for that same offset', () => {
    setTop(740);
    detach = attachScrollSequence(
      host,
      tiles,
      (el, e, i) => {
        const s = hingeStyle(e, i);
        if (!s) {
          el.style.transform = '';
          el.style.opacity = '';
          return;
        }
        el.style.transform = s.transform;
        el.style.opacity = s.opacity;
      },
      SEQ_PLAIN,
    );
    expect(tiles.map((t) => t.style.transform)).toEqual([
      'translateZ(-3.2px) rotateX(-3.81deg)',
      'translateZ(-16.9px) rotateY(-18.88deg)',
      'translateZ(-49.3px) rotateY(54.96deg)',
      'translateZ(-70.0px) rotateX(-84.00deg)',
      'translateZ(-70.0px) rotateY(78.00deg)',
      'translateZ(-70.0px) rotateY(-78.00deg)',
    ]);
    expect(tiles.map((t) => t.style.opacity)).toEqual([
      '1',
      '1',
      '0.62',
      '0',
      '0',
      '0',
    ]);
  });

  it('runs the weld profile further ahead at the same offset', () => {
    setTop(900);
    const seen: number[] = [];
    detach = attachScrollSequence(host, tiles, (_el, e) => seen.push(e), SEQ_WELD);
    // Golden: t = (1.21 - 0.9) / (1.21 - 0.576).
    expect(seen[0]).toBe(1); // tile 0 already finished and clears
    expect(seen[1]).toBeCloseTo(0.998_923_783_925_691_7, 12);
    expect(seen[4]).toBeCloseTo(0.264_960_414_191_446_56, 12);
    expect(seen[5]).toBe(0);
  });

  it('clamps progress at both ends', () => {
    setTop(5000); // far below the fold
    const low: number[] = [];
    const d1 = attachScrollSequence(host, tiles, (_e, e) => low.push(e), SEQ_PLAIN);
    expect(low).toEqual([0, 0, 0, 0, 0, 0]);
    d1();

    setTop(-5000); // scrolled well past
    const high: number[] = [];
    detach = attachScrollSequence(host, tiles, (_e, e) => high.push(e), SEQ_PLAIN);
    expect(high).toEqual([1, 1, 1, 1, 1, 1]);
  });

  it('falls back to the source defaults when opts are omitted', () => {
    setTop(740);
    const seen: number[] = [];
    detach = attachScrollSequence(host, tiles, (_el, e) => seen.push(e));
    // DEFAULTS: start 0.98, end 0.26, span 0.40, step 0.105.
    const t = (0.98 - 0.74) / (0.98 - 0.26);
    const u = Math.max(0, Math.min(1, t / 0.4));
    expect(seen[0]).toBeCloseTo(1 - Math.pow(1 - u, 3), 12);
  });

  it('observes the host with the source’s 140% root margin', () => {
    detach = attachScrollSequence(host, tiles, () => {}, SEQ_PLAIN);
    expect(ios).toHaveLength(1);
    expect(ios[0].init?.rootMargin).toBe('140% 0px 140% 0px');
    expect(ios[0].observed).toEqual([host]);
  });

  it('only starts the rAF loop once the host intersects', () => {
    detach = attachScrollSequence(host, tiles, () => {}, SEQ_PLAIN);
    expect(rafQueue).toHaveLength(0);
    fire(true);
    expect(rafQueue).toHaveLength(1);
    frame();
    expect(rafQueue).toHaveLength(1); // the loop re-arms itself
  });

  it('ignores an entry that repeats the state it is already in', () => {
    detach = attachScrollSequence(host, tiles, () => {}, SEQ_PLAIN);
    fire(true);
    rafQueue = [];
    fire(true);
    expect(rafQueue).toHaveLength(0);
  });

  it('scrubs toward the reading rather than snapping to it', () => {
    setTop(1000); // e = 0 everywhere
    const seen: number[] = [];
    detach = attachScrollSequence(host, tiles, (_el, e, i) => {
      if (i === 0) seen.push(e);
    }, SEQ_PLAIN);
    expect(seen[0]).toBe(0);

    fire(true);
    setTop(0); // jump to fully past — the raw reading is now 1
    frame();
    // One frame at scrub 0.14 lands cur at 0.14, NOT at 1.
    const u = 0.14 / 0.42;
    expect(seen[1]).toBeCloseTo(1 - Math.pow(1 - u, 3), 12);
  });

  it('SNAPS to the true position when the host leaves view', () => {
    setTop(1000);
    const seen: number[] = [];
    detach = attachScrollSequence(host, tiles, (_el, e, i) => {
      if (i === 0) seen.push(e);
    }, SEQ_PLAIN);
    fire(true);
    setTop(0);
    frame(); // eased part-way
    seen.length = 0;
    /* The fake cancelAnimationFrame only records the id; it cannot un-queue.
       Empty the queue by hand so the assertion below is about what the EXIT
       path schedules, not about what was already in flight. */
    rafQueue = [];

    fire(false);
    // The exit path does `cur = read()` then one un-scheduled tick, so tile 0
    // is at the true end of the run — no lerp, and no new frame queued.
    expect(seen).toEqual([1]);
    expect(rafQueue).toHaveLength(0);
    expect(ios[0].disconnected).toBe(false);
    expect(rafCancelled.length).toBeGreaterThan(0);
  });

  it('under reduced motion applies e=1 to every tile and never observes', () => {
    window.matchMedia = ((q: string) =>
      ({
        matches: q.includes('reduce'),
        media: q,
        addEventListener: () => {},
        removeEventListener: () => {},
      }) as unknown as MediaQueryList) as typeof window.matchMedia;

    const seen: number[] = [];
    detach = attachScrollSequence(host, tiles, (_el, e) => seen.push(e), SEQ_PLAIN);
    expect(seen).toEqual([1, 1, 1, 1, 1, 1]);
    expect(ios).toHaveLength(0);
    expect(rafQueue).toHaveLength(0);
  });

  it('detach disconnects the observer and cancels the pending frame', () => {
    detach = attachScrollSequence(host, tiles, () => {}, SEQ_PLAIN);
    fire(true);
    detach();
    detach = () => {};
    expect(ios[0].disconnected).toBe(true);
    expect(rafCancelled.length).toBeGreaterThan(0);
    frame(); // draining the stale callback must not re-arm the loop
    expect(rafQueue).toHaveLength(0);
  });
});
