#!/usr/bin/env node
/**
 * Regenerate src/styles/seo.css from the repository-root seo.css.
 *
 * The fourth stylesheet on the SEO-shell pages. The legacy <link> order is
 *
 *   /services/service.css -> /assets/footer.css -> /assets/nav.css -> /seo.css
 *
 * and /seo.css is where the material, guide and sitemap archetypes keep the
 * blocks service.css never had: `.mgrid`/`.mcard` (the materials hub grid),
 * `.facts`, `.price-line`, `.lead-answer`, `.appgrid`/`.app`, `.rel`/
 * `.rel-cols`, `.note`, `.chips`, `.tbl` and the `.sm-*` sitemap groups.
 *
 * Unlike content.css there is nothing to excise: the chrome is not in this
 * file, so the port is the whole thing, byte for byte.
 *
 * IT OVERRIDES service.css IN EXACTLY TWO PLACES, and both are same-selector
 * collisions that only the load order resolves:
 *
 *   .prose p    service.css 70ch  ->  seo.css 72ch     (the prose measure)
 *   .block h2   service.css sizing +  seo.css scroll-margin-top:90px
 *
 * The second merges; the first does not. Import seo.css before content.css and
 * every paragraph on these pages silently narrows by 2ch.
 *
 * Usage:  node scripts/port-seo-css.mjs [--check]
 *
 * `--check` regenerates into memory and exits non-zero if the file on disk
 * differs — for CI, or for anyone who suspects a hand-edit.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const WEB = resolve(HERE, '..');
const REPO = resolve(WEB, '..');

const SOURCE = join(REPO, 'seo.css');
const TARGET = join(WEB, 'src', 'styles', 'seo.css');

/** The first and last declarations, checked so a source edit cannot go quiet. */
const EXPECT_FIRST = '.lead-answer{';
const EXPECT_LAST = '.app p{font-size:12.8px;line-height:1.5;color:var(--muted);font-weight:300;margin:0}';

const BANNER = `/* ==========================================================================
   seo.css  —  the repository-root /seo.css, VERBATIM
   --------------------------------------------------------------------------
   The fourth sheet on the SEO-shell archetypes. The legacy <link> order is

     /services/service.css -> /assets/footer.css -> /assets/nav.css -> /seo.css

   which in this port is

     globals.css -> chrome.css -> content.css -> seo.css

   so this file must be imported AFTER content.css. Two selectors exist in
   both sheets and only the order decides them:

     .prose p    service.css max-width:70ch  ->  seo.css max-width:72ch
     .block h2   service.css type scale       +  seo.css scroll-margin-top

   Swap the imports and every prose paragraph on these pages narrows by 2ch.

   Everything here is byte-for-byte from the source file, in its source order.
   GENERATED by scripts/port-seo-css.mjs. Do not hand-edit; re-run it.
   (Line endings are normalised CRLF -> LF; nothing else is touched.)
   \`node scripts/port-seo-css.mjs --check\` fails if this file has drifted.
   ========================================================================== */

`;

function build() {
  const text = readFileSync(SOURCE, 'utf8').replace(/\r\n/g, '\n');
  const lines = text.split('\n');
  const last = [...lines].reverse().find((l) => l.trim() !== '');

  if (lines[0] !== EXPECT_FIRST || last !== EXPECT_LAST) {
    throw new Error(
      `seo.css has shifted: expected it to open with\n  ${EXPECT_FIRST}\n` +
        `and close with\n  ${EXPECT_LAST}\nbut found\n  ${lines[0]}\n  ${last}\n` +
        'Check the source before regenerating.',
    );
  }

  const css = `${BANNER}${text.replace(/\n*$/, '\n')}`;

  // A stylesheet that does not balance is a stylesheet that swallowed a rule.
  const open = (css.match(/\{/g) ?? []).length;
  const close = (css.match(/\}/g) ?? []).length;
  if (open !== close) {
    throw new Error(`unbalanced braces: ${open} open, ${close} close`);
  }
  return css;
}

const css = build();

if (process.argv.includes('--check')) {
  const onDisk = readFileSync(TARGET, 'utf8');
  if (onDisk !== css) {
    console.error(
      'seo.css has drifted from the root seo.css.\n' +
        'Run `node scripts/port-seo-css.mjs` and review the diff.',
    );
    process.exit(1);
  }
  console.log('seo.css matches the root seo.css.');
} else {
  writeFileSync(TARGET, css);
  console.log(`seo.css regenerated — ${css.split('\n').length} lines.`);
}
