/* GENERATED by scripts/extract-home-data.mjs from assets/site.js:179 — PROCESS, PROC_COPY, PROC_DETAIL. Do not hand-edit. */

/**
 * The four process steps, plus the copy that actually renders.
 *
 * PROCESS[n].d appears TWICE in the source object literal. The later key wins
 * in JS, so `d` here is the second string — matching what the legacy page has
 * always shown. The flow tiles do not read `d` at all; they read PROC_COPY,
 * which is a separate, shorter line per step. PROC_DETAIL is the modal body.
 */
export interface ProcessStep {
  t: string;
  img: string;
  /** The second `d:` in the source literal — the one JS keeps. */
  d: string;
  long: string;
}

export interface ProcessDetail {
  lede: string;
  /** [heading, body] pairs. */
  points: readonly (readonly [string, string])[];
}

export const PROCESS: readonly ProcessStep[] = [
  {
    "t": "Consultation",
    "img": "/assets/site/process-consult-shake-1600.webp",
    "d": "Understanding your space and style.",
    "long": "We start at your kitchen, understanding the space, how you live in it, and the look you're after, then guide you to the material and finish that fit, with no pressure and no jargon."
  },
  {
    "t": "Design & Quote",
    "img": "/assets/site/process-quote-plans-1600.webp",
    "d": "A clear, itemised plan and price.",
    "long": "We plan the layout, edge profiles, joints and cut-outs, then give you a clear, itemised quote covering template, fabrication and installation, the price you see is the price you pay."
  },
  {
    "t": "Template & Craft",
    "img": "/assets/site/process-template-678.webp",
    "d": "Measured and cut to the millimetre.",
    "long": "Once your units are level we template the space by hand to a fraction of a millimetre. Your slab is then precision-cut and polished by our own experienced fabricators, cut wet to full safety standards, with the veining matched through the joints before we fit it ourselves."
  },
  {
    "t": "Install & Enjoy",
    "img": "/assets/site/process-install-hands-1516.webp",
    "d": "Fitted cleanly, usually within days.",
    "long": "Our team fits your worktop cleanly and precisely, usually within days of templating, squared, sealed and ready to use. Then the kitchen is yours to enjoy."
  }
];

/** site.js:193 — the one-liner under each tile's heading. */
export const PROC_COPY: readonly string[] = [
  "We visit, look at the space, and help you choose.",
  "One itemised price, agreed before anything is cut.",
  "Templated by us, cut and polished to that template.",
  "Fitted and sealed, usually within days."
];

/** site.js:243 — the "Read more" modal for each step. */
export const PROC_DETAIL: readonly ProcessDetail[] = [
  {
    "lede": "A free home visit, usually about an hour, in the room the worktop is going into. No obligation and nobody trying to close you on the day.",
    "points": [
      [
        "What happens",
        "We look at the space together, talk through how you actually use the kitchen, and measure roughly so we can price it properly."
      ],
      [
        "What we bring",
        "Samples, so you can see the stone in your own light rather than under a showroom spotlight."
      ],
      [
        "What you get",
        "An honest steer on the material that suits your life, including when the cheaper option is the better one."
      ]
    ]
  },
  {
    "lede": "One clear, itemised quote, put together after the visit and explained line by line. The price we agree is the price you pay.",
    "points": [
      [
        "What we plan",
        "Layout, edge profiles, where the joints fall and how they are vein matched, plus every cut-out."
      ],
      [
        "What is included",
        "Template, fabrication, fitting and VAT. Cut-outs, drainer grooves and pencil edges come as standard, not as extras."
      ],
      [
        "What happens next",
        "Nothing until you say so. We only order and cut once you have approved the quote and the slab."
      ]
    ]
  },
  {
    "lede": "The precise part. We template off your real cabinets, then your slab is cut and polished to that template.",
    "points": [
      [
        "Templating",
        "Measured by hand to a fraction of a millimetre, once the units are level and secure. Getting this right is what stops surprises on fitting day."
      ],
      [
        "In the workshop",
        "Your slab is cut wet to current HSE standards and polished by hand, with the veining matched across every joint before it leaves us."
      ],
      [
        "Your slab",
        "You approve the actual piece from photographs first, so the stone you chose is the stone that arrives."
      ]
    ]
  },
  {
    "lede": "Fitting day, usually within days of templating. Our own team, on the date we agreed.",
    "points": [
      [
        "On the day",
        "Floors protected, the worktop squared, sealed and the joints finished on site. Most kitchens are done inside a day."
      ],
      [
        "Before we leave",
        "We walk it with you and sign it off together, and take the packaging away with us."
      ],
      [
        "Afterwards",
        "A ten-year guarantee in writing, and if anything needs attention we are back on site inside 72 hours."
      ]
    ]
  }
];
