/* GENERATED by scripts/extract-home-data.mjs from assets/site.js:2019 — PROJECTS. Do not hand-edit. */

/**
 * The eight gallery projects. `gallery` entries are [url, width, height] —
 * the intrinsic dimensions matter because the lightbox sizes its stage from
 * the aspect ratio before the image has loaded.
 */
export interface Project {
  key: string;
  name: string;
  place: string;
  /** Display URL for the door/tile; look it up in SRCSET. */
  img: string;
  brand: boolean;
  /** Shown in the detail view's meta row; omitted when empty. */
  type: string;
  /** "What we did" paragraph. Empty on projects with no write-up yet. */
  story: string;
  /** Name of the REVIEWS entry to pull into the detail view, when there is one. */
  reviewBy?: string;
  gallery: readonly (readonly [string, number, number])[];
}

export const PROJECTS: readonly Project[] = [
  {
    "key": "wimbledon",
    "name": "The Wimbledon Project",
    "place": "Wimbledon, London",
    "img": "/assets/projects/wimbledon-1400.webp",
    "brand": true,
    "type": "Worktops and splashbacks, across multiple apartments",
    "story": "A development of several apartments, each one templated and fitted on its own. The worktops and full height splashbacks run through every flat in the same stone, so the block reads as one piece of work rather than a set of separate kitchens.",
    "reviewBy": "Kinga Skubiszewska",
    "gallery": [
      [
        "/assets/projects/wimbledon-g1.webp",
        1067,
        1600
      ],
      [
        "/assets/projects/wimbledon-g2.webp",
        1067,
        1600
      ],
      [
        "/assets/projects/wimbledon-g3.webp",
        1067,
        1600
      ],
      [
        "/assets/projects/wimbledon-g4.webp",
        1067,
        1600
      ],
      [
        "/assets/projects/wimbledon-g5.webp",
        1067,
        1600
      ],
      [
        "/assets/projects/wimbledon-g6.webp",
        1067,
        1600
      ],
      [
        "/assets/projects/wimbledon-g7.webp",
        1067,
        1600
      ],
      [
        "/assets/projects/wimbledon-g8.webp",
        1067,
        1600
      ],
      [
        "/assets/projects/wimbledon-g9.webp",
        1067,
        1600
      ],
      [
        "/assets/projects/wimbledon-g10.webp",
        1067,
        1600
      ],
      [
        "/assets/projects/wimbledon-g11.webp",
        1067,
        1600
      ]
    ]
  },
  {
    "key": "watford",
    "name": "The Watford Project",
    "place": "Watford",
    "img": "/assets/projects/watford-1400.webp",
    "brand": true,
    "type": "Worktop and splashback",
    "story": "",
    "gallery": [
      [
        "/assets/projects/watford-g1.webp",
        1600,
        1066
      ],
      [
        "/assets/projects/watford-g2.webp",
        1600,
        1066
      ],
      [
        "/assets/projects/watford-g3.webp",
        1600,
        1066
      ],
      [
        "/assets/projects/watford-g4.webp",
        1600,
        1066
      ],
      [
        "/assets/projects/watford-g5.webp",
        1600,
        1066
      ],
      [
        "/assets/projects/watford-g6.webp",
        1600,
        1066
      ],
      [
        "/assets/projects/watford-g7.webp",
        1600,
        1067
      ],
      [
        "/assets/projects/watford-g8.webp",
        1600,
        1067
      ],
      [
        "/assets/projects/watford-g9.webp",
        1600,
        1067
      ],
      [
        "/assets/projects/watford-g10.webp",
        1600,
        1067
      ],
      [
        "/assets/projects/watford-g11.webp",
        1600,
        1067
      ],
      [
        "/assets/projects/watford-g12.webp",
        1600,
        1067
      ],
      [
        "/assets/projects/watford-g13.webp",
        1600,
        1067
      ],
      [
        "/assets/projects/watford-g14.webp",
        1600,
        1067
      ],
      [
        "/assets/projects/watford-g15.webp",
        1600,
        1067
      ],
      [
        "/assets/projects/watford-g16.webp",
        1600,
        1067
      ],
      [
        "/assets/projects/watford-g17.webp",
        1600,
        1067
      ],
      [
        "/assets/projects/watford-g18.webp",
        1600,
        1067
      ]
    ]
  },
  {
    "key": "hornchurch",
    "name": "The Hornchurch Project",
    "place": "Essex",
    "img": "/assets/projects/hornchurch-1400.webp",
    "brand": true,
    "type": "Worktop, island and splashbacks",
    "story": "Taj Mahal quartzite at 30mm, across the worktop, the island and the splashbacks, with a single ogee edge worked through the run.",
    "gallery": [
      [
        "/assets/projects/hornchurch-g1.webp",
        882,
        1177
      ],
      [
        "/assets/projects/hornchurch-g4.webp",
        1569,
        1177
      ],
      [
        "/assets/projects/hornchurch-g5.webp",
        1569,
        1177
      ],
      [
        "/assets/projects/hornchurch-g7.webp",
        1200,
        1600
      ],
      [
        "/assets/projects/hornchurch-g8.webp",
        1200,
        1600
      ],
      [
        "/assets/projects/hornchurch-g9.webp",
        1200,
        1600
      ],
      [
        "/assets/projects/hornchurch-g10.webp",
        1200,
        1600
      ]
    ]
  },
  {
    "key": "rickmansworth",
    "name": "The Rickmansworth Project",
    "place": "Rickmansworth",
    "img": "/assets/projects/rickmansworth-1400.webp",
    "brand": true,
    "type": "Worktop and splashback",
    "story": "",
    "gallery": [
      [
        "/assets/projects/rickmansworth-g1.webp",
        1084,
        1446
      ],
      [
        "/assets/projects/rickmansworth-g2.webp",
        1084,
        1446
      ],
      [
        "/assets/projects/rickmansworth-g3.webp",
        1084,
        1446
      ],
      [
        "/assets/projects/rickmansworth-g4.webp",
        1084,
        1446
      ],
      [
        "/assets/projects/rickmansworth-g5.webp",
        1084,
        1446
      ],
      [
        "/assets/projects/rickmansworth-g6.webp",
        1084,
        1446
      ],
      [
        "/assets/projects/rickmansworth-g7.webp",
        1200,
        1600
      ],
      [
        "/assets/projects/rickmansworth-g8.webp",
        1200,
        1600
      ],
      [
        "/assets/projects/rickmansworth-g9.webp",
        1200,
        1600
      ],
      [
        "/assets/projects/rickmansworth-g10.webp",
        1200,
        1600
      ],
      [
        "/assets/projects/rickmansworth-g11.webp",
        1200,
        1600
      ],
      [
        "/assets/projects/rickmansworth-g12.webp",
        1200,
        1600
      ],
      [
        "/assets/projects/rickmansworth-g13.webp",
        1200,
        1600
      ],
      [
        "/assets/projects/rickmansworth-g14.webp",
        1200,
        1600
      ],
      [
        "/assets/projects/rickmansworth-g15.webp",
        1200,
        1600
      ]
    ]
  },
  {
    "key": "ruislip",
    "name": "The Ruislip Project",
    "place": "Ruislip, Hillingdon",
    "img": "/assets/projects/ruislip-1400.webp",
    "brand": true,
    "type": "Worktop, splashback, breakfast bar and arches",
    "story": "Calacatta Sydney Black quartz at 20mm, across the worktop, the island and the splashbacks. The breakfast bar was cut to the room, and the doorway into the kitchen lined in the same stone so the run carries through.",
    "gallery": [
      [
        "/assets/projects/ruislip-g1.webp",
        1067,
        1600
      ],
      [
        "/assets/projects/ruislip-g2.webp",
        1067,
        1600
      ],
      [
        "/assets/projects/ruislip-g3.webp",
        1067,
        1600
      ],
      [
        "/assets/projects/ruislip-g4.webp",
        1067,
        1600
      ],
      [
        "/assets/projects/ruislip-g5.webp",
        1067,
        1600
      ],
      [
        "/assets/projects/ruislip-g6.webp",
        1067,
        1600
      ]
    ]
  },
  {
    "key": "central-london",
    "name": "The Central London Project",
    "place": "London",
    "img": "/assets/projects/central-london-1400.webp",
    "brand": true,
    "type": "Worktop",
    "story": "",
    "reviewBy": "Joel Brizman",
    "gallery": [
      [
        "/assets/projects/central-london-g1.webp",
        1600,
        1067
      ],
      [
        "/assets/projects/central-london-g2.webp",
        1600,
        1067
      ],
      [
        "/assets/projects/central-london-g3.webp",
        1600,
        1067
      ],
      [
        "/assets/projects/central-london-g4.webp",
        1600,
        1067
      ],
      [
        "/assets/projects/central-london-g5.webp",
        1600,
        1067
      ],
      [
        "/assets/projects/central-london-g6.webp",
        1600,
        1067
      ],
      [
        "/assets/projects/central-london-g7.webp",
        1600,
        1067
      ],
      [
        "/assets/projects/central-london-g8.webp",
        1600,
        1067
      ],
      [
        "/assets/projects/central-london-g9.webp",
        1600,
        1067
      ],
      [
        "/assets/projects/central-london-g10.webp",
        1600,
        1067
      ],
      [
        "/assets/projects/central-london-g11.webp",
        1600,
        1067
      ],
      [
        "/assets/projects/central-london-g12.webp",
        1600,
        1067
      ],
      [
        "/assets/projects/central-london-g13.webp",
        1600,
        1067
      ]
    ]
  },
  {
    "key": "harlow",
    "name": "The Harlow Project",
    "place": "Essex",
    "img": "/assets/projects/harlow-1400.webp",
    "brand": true,
    "type": "Worktop and splashback",
    "story": "",
    "gallery": [
      [
        "/assets/projects/harlow-g1.webp",
        1084,
        1446
      ],
      [
        "/assets/projects/harlow-g2.webp",
        882,
        1177
      ],
      [
        "/assets/projects/harlow-g3.webp",
        1084,
        1446
      ],
      [
        "/assets/projects/harlow-g4.webp",
        1084,
        1446
      ],
      [
        "/assets/projects/harlow-g5.webp",
        1084,
        1446
      ],
      [
        "/assets/projects/harlow-g6.webp",
        1084,
        1446
      ],
      [
        "/assets/projects/harlow-g8.webp",
        1200,
        1600
      ],
      [
        "/assets/projects/harlow-g9.webp",
        1200,
        1600
      ],
      [
        "/assets/projects/harlow-g10.webp",
        1200,
        1600
      ],
      [
        "/assets/projects/harlow-g11.webp",
        1200,
        1600
      ],
      [
        "/assets/projects/harlow-g12.webp",
        1200,
        1600
      ],
      [
        "/assets/projects/harlow-g13.webp",
        1200,
        1600
      ],
      [
        "/assets/projects/harlow-g14.webp",
        1200,
        1600
      ],
      [
        "/assets/projects/harlow-g15.webp",
        1200,
        1600
      ]
    ]
  },
  {
    "key": "harrow",
    "name": "The Harrow Project",
    "place": "Harrow",
    "img": "/assets/projects/harrow-1400.webp",
    "brand": true,
    "type": "Worktop",
    "story": "",
    "gallery": [
      [
        "/assets/projects/harrow-g1.webp",
        1084,
        1446
      ],
      [
        "/assets/projects/harrow-g2.webp",
        1084,
        1446
      ]
    ]
  }
];
