/* GENERATED by scripts/extract-home-data.mjs from assets/site.js — the SS map. Do not hand-edit. */

/**
 * The legacy responsive-image table. site.js builds every card's `srcset`
 * through `ss(url, sizes)` (site.js:112), which looks the *display* URL up in
 * this map and emits nothing when there is no entry — a plain `src` with no
 * srcset at all. `srcSet()` below reproduces that exactly, including the
 * "no entry, no attribute" case, because a srcset invented for a URL the map
 * does not list would point at files that are not on the server.
 */
export const SRCSET: Readonly<Record<string, string>> = {
  "/assets/projects/ruislip-1400.webp": "/assets/projects/ruislip-560.webp 560w, /assets/projects/ruislip-1400.webp 1400w",
  "/assets/projects/central-london-1400.webp": "/assets/projects/central-london-560.webp 560w, /assets/projects/central-london-1400.webp 1400w",
  "/assets/projects/hornchurch-1400.webp": "/assets/projects/hornchurch-560.webp 560w, /assets/projects/hornchurch-1400.webp 1400w",
  "/assets/projects/harrow-1400.webp": "/assets/projects/harrow-560.webp 560w, /assets/projects/harrow-1400.webp 1400w",
  "/assets/projects/harlow-1400.webp": "/assets/projects/harlow-560.webp 560w, /assets/projects/harlow-1400.webp 1400w",
  "/assets/projects/rickmansworth-1400.webp": "/assets/projects/rickmansworth-560.webp 560w, /assets/projects/rickmansworth-1400.webp 1400w",
  "/assets/projects/watford-1400.webp": "/assets/projects/watford-560.webp 560w, /assets/projects/watford-1400.webp 1400w",
  "/assets/projects/wimbledon-1400.webp": "/assets/projects/wimbledon-560.webp 560w, /assets/projects/wimbledon-1400.webp 1400w",
  "/assets/site/hero-night-2752.webp": "/assets/site/hero-night-1400.webp 1400w, /assets/site/hero-night-2000.webp 2000w, /assets/site/hero-night-2752.webp 2752w",
  "/assets/site/cta-slab-2752.webp": "/assets/site/cta-slab-1958.webp 1958w, /assets/site/cta-slab-2752.webp 2752w",
  "/assets/site/kitchen-day-1188.webp": "/assets/site/kitchen-day-626.webp 626w, /assets/site/kitchen-day-1188.webp 1188w",
  "/assets/site/quarry-955.webp": "/assets/site/quarry-518.webp 518w, /assets/site/quarry-955.webp 955w",
  "/assets/site/service-dining-2400.webp": "/assets/site/service-dining-880.webp 880w, /assets/site/service-dining-1600.webp 1600w, /assets/site/service-dining-2400.webp 2400w",
  "/assets/site/service-bathrooms-2400.webp": "/assets/site/service-bathrooms-880.webp 880w, /assets/site/service-bathrooms-1600.webp 1600w, /assets/site/service-bathrooms-2400.webp 2400w",
  "/assets/site/service-outdoor-2400.webp": "/assets/site/service-outdoor-880.webp 880w, /assets/site/service-outdoor-1600.webp 1600w, /assets/site/service-outdoor-2400.webp 2400w",
  "/assets/site/service-fireplaces-1550.webp": "/assets/site/service-fireplaces-880.webp 880w, /assets/site/service-fireplaces-1550.webp 1550w",
  "/assets/site/service-vanity-2400.webp": "/assets/site/service-vanity-880.webp 880w, /assets/site/service-vanity-1600.webp 1600w, /assets/site/service-vanity-2400.webp 2400w",
  "/assets/site/service-commercial-bar-2400.webp": "/assets/site/service-commercial-bar-880.webp 880w, /assets/site/service-commercial-bar-1600.webp 1600w, /assets/site/service-commercial-bar-2400.webp 2400w",
  "/assets/site/service-splash-hob-1200.webp": "/assets/site/service-splash-hob-880.webp 880w, /assets/site/service-splash-hob-1200.webp 1200w",
  "/assets/site/service-worktops-quartz-2400.webp": "/assets/site/service-worktops-quartz-880.webp 880w, /assets/site/service-worktops-quartz-1600.webp 1600w, /assets/site/service-worktops-quartz-2400.webp 2400w",
  "/assets/site/process-quote-plans-1600.webp": "/assets/site/process-quote-plans-880.webp 880w, /assets/site/process-quote-plans-1600.webp 1600w",
  "/assets/site/about-fitting-386.webp": "/assets/site/about-fitting-248.webp 248w, /assets/site/about-fitting-386.webp 386w",
  "/assets/site/process-consult-shake-1600.webp": "/assets/site/process-consult-shake-880.webp 880w, /assets/site/process-consult-shake-1600.webp 1600w",
  "/assets/site/process-install-hands-1516.webp": "/assets/site/process-install-hands-880.webp 880w, /assets/site/process-install-hands-1516.webp 1516w",
  "/assets/site/about-handshake-900.webp": "/assets/site/about-handshake-600.webp 600w, /assets/site/about-handshake-900.webp 900w",
  "assets/team/handshake.jpg": "/assets/site/team-handshake-600.webp 600w, /assets/site/team-handshake-900.webp 900w",
  "assets/team/samples.jpg": "/assets/site/team-samples-248.webp 248w, /assets/site/team-samples-386.webp 386w",
  "assets/team/fitting.jpg": "/assets/site/team-fitting-248.webp 248w, /assets/site/team-fitting-386.webp 386w"
};

/** site.js:112 — `function ss(u,z)`. Returns props, not an attribute string. */
export function srcSet(
  url: string | undefined,
  sizes: string,
): { srcSet: string; sizes: string } | Record<string, never> {
  const s = url ? SRCSET[url] : undefined;
  return s ? { srcSet: s, sizes } : {};
}
