import { chromium } from 'playwright';
const b=await chromium.launch({channel:'chrome'});
const p=await b.newPage({viewport:{width:1440,height:900}});
const out=[];
p.on('console',m=>{const t=m.text(); if(/hydrat|didn't match|server rendered/i.test(t)) out.push(t);});
p.on('pageerror',e=>{const t=String(e); if(/hydrat|didn't match/i.test(t)) out.push(t);});
await p.goto('http://localhost:3000'+(process.argv[2]||'/trade'),{waitUntil:'domcontentloaded'});
await p.waitForTimeout(2500);
console.log(out.length?out.join('\n\n---\n\n').slice(0,3000):'NO HYDRATION ERRORS');
await b.close();
