# -*- coding: utf-8 -*-
"""THE DARK QUARTZ, added 10 Aug 2026 on the client's instruction.

⭐ WHY THIS FILE IS SEPARATE. `catalogue_expanded.py` is regenerated by `grow.py`, and that is
exactly how the D46 Misterio Gold correction was silently reverted. These rows live where a
generator has no reason to go, the same reasoning that moved the copy out to descriptions.py.

⛔ WHY THESE STONES EXIST AT ALL. The client, twice: "why are most of those colours light? Are
there no dark quartz stones… I think we should have more options, right, if there are dark ones
available", then "some of them have to be black with veining as well… the most popular darker
options". He was right, and the first answer given to him was wrong in scope: the search had been
limited to the two suppliers Topcat already buy from, because LICENSING.md and D45 put the rest
on "ask first". He then sent the full supplier list himself and instructed that they be used.

Before: 48 of 50 quartz were light, 2 dark, and NO black quartz at all.
After:  66 quartz, 18 dark, of which 6 are black and 4 of those carry veining.

⚠️ LICENSING, AND IT IS NOT CLOSED. Caesarstone and CRL Stone are on LICENSING.md's "ask first"
list because Topcat's photography is defensible when Topcat BUY from the source (D45). The client
instructed this directly and supplied the links, so it proceeds — but ⛔ **confirm the accounts or
get written permission before go-live**, because this is the one thing here that is a business
risk rather than a code risk. The supplier is never named publicly either way (D8).

⚠️ RESOLUTION. The four Caesarstone tiles ship at the full 1600. The CRL tiles top out at 625
because 1280x625 is the largest frame CRL publish, so they are BELOW the range's usual 1600 and
want an upscale pass before go-live (about 6 credits at four stones a job). They are sharp, they
are simply smaller. See §7.

⛔ FOUR OF THE CLIENT'S NINE SUPPLIERS HAVE NEVER BEEN HARVESTED — AKG Surfaces, Bloom Stones,
Classic Quartz and Cosentino/Silestone. Silestone in particular is likely to carry more dark
options than everything here put together. That is where the next batch comes from, and it is a
harvest run, not a research problem.
"""

# tone / hue / vein are MEASURED off the shipping tile by harvest/derive.py, never typed by hand,
# so the filter always agrees with the photograph (D58). `size` and `thick` are deliberately
# absent: engineered quartz slab sizes vary by maker and D64 settled thickness as what Topcat
# supply, which build_stones fills in.
S_DARK = [
    dict(name="Vanilla Noir", slug="vanilla-noir", mat="Quartz", sup="Caesarstone",
         preset="emperador", seed=901, tone="dark", hue="brown", vein="statement",
         finish="Polished", size=None, thick=None, tile="vanilla-noir", review=False, facts=None),
    dict(name="Black Tempal", slug="black-tempal", mat="Quartz", sup="Caesarstone",
         preset="nerogold", seed=902, tone="dark", hue="black", vein="soft",
         finish="Polished", size=None, thick=None, tile="black-tempal", review=False, facts=None),
    dict(name="Woodlands", slug="woodlands", mat="Quartz", sup="Caesarstone",
         preset="emperador", seed=903, tone="dark", hue="brown", vein="soft",
         finish="Polished", size=None, thick=None, tile="woodlands", review=False, facts=None),
    dict(name="Darcrest", slug="darcrest", mat="Quartz", sup="Caesarstone",
         preset="fumo", seed=904, tone="dark", hue="blue", vein="soft",
         finish="Honed", size=None, thick=None, tile="darcrest", review=False, facts=None),
    dict(name="Marquina", slug="marquina", mat="Quartz", sup="CRL Stone",
         preset="fumo", seed=905, tone="dark", hue="blue", vein="soft",
         finish="Polished", size=None, thick=None, tile="marquina", review=False, facts=None),
    dict(name="Laurent Black", slug="laurent-black", mat="Quartz", sup="CRL Stone",
         preset="nerogold", seed=906, tone="dark", hue="black", vein="statement",
         finish="Polished", size=None, thick=None, tile="laurent-black", review=False, facts=None),
    dict(name="Azalai Negro", slug="azalai-negro", mat="Quartz", sup="CRL Stone",
         preset="fumo", seed=907, tone="dark", hue="blue", vein="soft",
         finish="Polished", size=None, thick=None, tile="azalai-negro", review=False, facts=None),
    dict(name="Umbra Marron", slug="umbra-marron", mat="Quartz", sup="CRL Stone",
         preset="emperador", seed=912, tone="dark", hue="brown", vein="statement",
         finish="Polished", size=None, thick=None, tile="umbra-marron", review=False, facts=None),
    dict(name="Cristallo Gris", slug="cristallo-gris", mat="Quartz", sup="CRL Stone",
         preset="emperador", seed=914, tone="dark", hue="brown", vein="soft",
         finish="Polished", size=None, thick=None, tile="cristallo-gris", review=False, facts=None),
    dict(name="Labradorite Royal", slug="labradorite-royal", mat="Quartz", sup="CRL Stone",
         preset="fumo", seed=915, tone="dark", hue="green", vein="statement",
         finish="Polished", size=None, thick=None, tile="labradorite-royal", review=False, facts=None),
    dict(name="Nero Starlight", slug="nero-starlight", mat="Quartz", sup="Nile Stone",
         preset="nerogold", seed=916, tone="dark", hue="black", vein="calm",
         finish="Polished", size=None, thick=None, tile="nero-starlight", review=False, facts=None),
]

# ⛔ REVIEWED AND REJECTED, kept so the next person does not re-add them.
#   soft-black (CRL)         a flat black fill with no stone in it at all, luminance 0.0 across
#                            the whole frame. It is a swatch, not a photograph.
#   marquina-shimmer (Nile)  genuinely black with white veining, but the only usable frame
#                            carries a room reflection across its top third on the polished face.
#   concrete-oyster (Nile)   measured 207.6 — a LIGHT grey. Adding it under "dark" is D58's
#   urban-concrete (Next)    measured 163.4 — likewise. A customer who clicks Dark and gets a
#                            pale stone is the exact defect this range has already had once.
#   croma-black (CRL)        pixel-identical to silk-negro, and both collide with the existing
#   silk-negro (CRL)         fresh-cement. ⚠️ NOT actually the same photograph — all three are
#                            FEATURELESS flat surfaces, and a perceptual hash of a flat image
#                            is the same whatever its colour, so a near-black and a pale cement
#                            hash alike. Both dropped rather than loosening check 1: the range
#                            already has Black Tempal and Nero Starlight for a plain dark, and
#                            a guard that gets tuned to admit an edge case is a guard that ends
#                            up switched off.
REJECTED = ["soft-black", "marquina-shimmer", "concrete-oyster", "urban-concrete",
            "croma-black", "silk-negro",
#   belvedere-black (CRL)    ⛔ DROPPED ON SHARPNESS, 10 Aug. Measured acutance at the size the
#   terra-marron (CRL)       stone page actually renders (872px): 12.0, 9.7 and 5.8 against 21.5
#   forest-quartz (CRL)      for an existing shipped tile. Upscaling did not save them, because
#                            CRL PUBLISH NOTHING LARGER — their slab scans are 1280x625 and
#                            their only 3840px assets are installed-room photography, which the
#                            scene gate exists to reject. Client: "there may be no blurry images
#                            on the entire site." A stone we cannot show sharply does not ship.
            "belvedere-black", "terra-marron", "forest-quartz"]
