# -*- coding: utf-8 -*-
"""The stone descriptions. One per slug, written against the photograph we actually ship.

⛔ THE RULE, from the client, 10 Aug 2026: DESCRIBE THE COLOUR AND THE PATTERN, NOTHING ELSE.

    "Just describe the colour of the stone. Don't talk about things like, oh, it can match to
    another stone or make promises we do not guarantee that we can fulfil. Only write about the
    way that it looks that someone might search."

So there is nothing here about sealing, heat, porosity, durability, which room it suits, how it
takes a joint, or what it pairs with. Every one of those is either a promise, a piece of advice
that varies by job, or a claim that belongs in the estimator and the guides. ⚠️ They were in an
earlier draft of these and were cut on the client's instruction. Do not put them back.

⭐ WHY THIS FILE EXISTS SEPARATELY. These used to sit inline in catalogue_expanded.py, which is
regenerated by grow.py — that is how the D46 Misterio Gold correction was silently reverted. Copy
lives here, and grow.py has no reason to touch it.

⛔ WHERE THE WORDS COME FROM, AND WHERE THEY MAY NOT.
  · The shipping tile in assets/slabs. Every line below was written with the photograph open,
    and it describes THAT crop, because that is what the customer is looking at.
  · Nothing else. ⚠️ NEITHER SUPPLIER PUBLISHES ANY PRODUCT COPY — checked 10 Aug: Nile's
    description field returns "Click on the image to enlarge" for all 138 products, and Next
    Stone Slabs has no product pages at all. There was nothing to reword.
  · ⛔ NEVER the open web for an engineered quartz. "Calacatta Classic" is a manufacturer's
    marketing name and a different maker's slab answers to it, so a description looked up
    elsewhere is somebody else's product under our name. Same reasoning as D45.

⚠️ IF A TILE IS RECROPPED OR REPLACED, ITS LINE HERE IS STALE. The description is of that
photograph. Re-read it against the new one.
"""

D = {
    # ---------------------------------------------------------------- QUARTZ
    "almond-beige": "A warm beige, almost plain, with a soft clouding of lighter and darker tone across it.",
    "arabescato-capri": "White with grey veining that forks and doubles back on itself, a thin brown line following the larger veins.",
    "arabescato-elegance": "Bright white with grey veining in long angular runs that break into finer branches at the edges.",
    "azul-shimmer": "A pale cool grey, close to white, with fine darker grey veining drifting across it.",
    "borghini-royal": "An off white carrying grey veins with warm gold running alongside them.",
    "blue-lagoon": "A grey surface broken up by angular blue and violet fragments, closer to shattered stone than to veining.",
    "calacatta-fantastico": "Bright white with broad grey veining and warm amber running beside it, one of the boldest patterns in the range.",
    "calacatta-oro-quartz": "A soft white crossed by fine veining in rose and warm copper rather than yellow gold.",
    "calacatta-gold-soft": "An off white with gold veining held back to a whisper, fine and widely spaced.",
    "grigio-fantasy": "A grey green surface covered in a dense network of fine dark lines.",
    "concrete-earth": "A pale warm grey with a faint pink and cream mottling, close to plain concrete.",
    "cloud-burst": "White with soft blue grey banding drifting diagonally across it and a fine sparkle in the surface.",
    "carrara-shimmer": "A bright white with a fine grey speckle scattered evenly through it and a faint sparkle.",
    "carrara-jumbo": "White with soft grey veining, fine and widely spread rather than bold.",
    "sahara-dunes": "A cream surface cut by broad bands of brown and grey, thick edged and irregular.",
    "crema-evora": "A pale cream with a warm pink cast and almost no pattern in it.",
    "crema-venato": "A very pale cool white with fine grey veining running in one direction.",
    "crema-tempest": "A soft white with olive and gold veining gathering and scattering across it.",
    "arabescato-gold": "Bright white with gold veining and grey shadowing alongside it.",
    "sabbia-beige": "A muted greenish beige with a fine streaked texture running horizontally.",
    "arabescato-grey": "White broken by grey veining with a faint lilac cast, forming rounded shapes across the slab.",
    "tuscany-supreme": "A warm white with olive green and grey veining in broad connected runs.",
    "misterio-gold": "A pale, near plain surface with fine gold brown veining that shows only at close range.",
    "fresh-cement": "A plain warm white with a very fine grain and no veining.",
    "white-eclypse": "White with heavy grey veining running the length of the slab in broad connected shapes.",
    "calacatta-exotic": "A clean white with grey veining, fine and evenly spread.",
    "cremo-delicato": "An off white with soft grey veining drifting diagonally.",
    "repen": "A mid brown taupe with a fine dark speckle scattered through it and no veining.",
    "calacatta-gold-shimmer": "A pale white with a cool lilac cast and grey veining in broad soft runs.",
    "corchia-gold": "White with gold and grey veining knotting together in irregular clusters.",
    "bianco-glacier": "White with soft grey veining that blurs into the surface like cloud.",
    "taj-mahal-elegance": "A warm apricot beige, almost plain, with a faint horizontal grain.",
    "arabescato-faniello": "An off white with fine grey veining spread thinly across it.",
    "corchia-light": "A pale grey with a green cast and fine darker veining forming rounded shapes.",
    "calacatta-supreme": "A clean white with grey veining in long diagonal runs.",
    "royal-grey": "A dark charcoal with a fine even grain and no veining.",
    "london-grey": "A plain mid grey with a very faint clouding and no veining.",
    "bianco-starlight": "A bright white with a fine sparkle worked through the surface.",
    "grigio-starlight": "A mid grey with a fine white speckle scattered evenly across it.",
    "calacatta-luna": "A warm white with olive gold veining forming wide open shapes.",
    "grigio-shimmer": "A warm mushroom grey with a fine sparkle and no veining.",
    "arabescato-classico": "A bright white with faint grey veining, very quiet across the slab.",
    "calacatta-borghini-light": "White with grey veining and a thin copper line following it.",
    "argento": "A white with a soft pink cast and fine grey veining across it.",
    "calacatta-classic": "Bright white with soft grey veining that fades at its edges rather than cutting a hard line.",
    "calacatta-lucente": "A pale white with a cool cast and soft grey veining, very lightly drawn.",
    "calacatta-aurelia": "White with grey veining and warm gold picking out the finer branches.",
    "calacatta-soft-shimmer": "White with fine gold brown veining running diagonally in thin threads.",
    "calacatta-grey-classic": "A clean white with fine grey veining, sparse and widely spaced.",
    "crema-d-aizhi": "A warm grey beige, almost plain, with a faint horizontal grain.",

    # ---------------------------------------------------------------- MARBLE
    "arabescato-vagli-oro": "White with dense grey veining forming a close network across the slab.",
    "calacatta-gold-oro": "A white marble with warm gold and grey veining running across it.",
    "calacatta-viola": "White cut through with dramatic purple and charcoal veining.",
    "calacatta-vagli-oro": "A cream white with brown and purple veining framing large pale shapes.",
    "fantastico-arni": "White and grey in flowing directional bands, folded rather than veined.",
    "nero-marquina": "Black with sharp white veining crossing it in a fine network.",
    "rainforest-brown": "A green grey surface threaded with dense red brown veining that branches like roots.",
    "verde-guatemala": "A deep green with darker green and black veining running through it.",
    "travertine-romano-classico": "A cream and beige stone laid in fine horizontal bands.",
    "carrara-honed": "A pale grey white with soft veining spread evenly, matt rather than glossy.",
    "bianco-eclypsia-calacatta": "White with fine charcoal veining scattered across it.",
    "belvedere-leather": "Black with gold and olive striations in horizontal layers, textured rather than glossy.",
    "blue-roma": "A pale grey blue crossed by brown gold veining in sharp angular lines.",
    "cristallo": "A warm honey brown, translucent in places, with dark fracture lines running across it.",
    "fusion-blue-leather": "Grey, brown and olive laid in flowing horizontal layers, textured rather than glossy.",
    "fusion-black": "Black with heavy gold and copper striations running across it in flowing layers.",
    "lemurian-blue": "A dark blue teal with a dense fine speckle through it.",
    "patagonia": "Large angular white and cream fragments set against translucent grey, with dark seams between them.",
    "taj-mahal": "A pale cream with a warm pink cast and very faint veining.",
    "venaria-reale": "A white and pink surface with brown gold veining flowing across it.",
    "arabescato-corchia-extra-honed": "Rounded white shapes set in a grey and violet matrix, matt rather than glossy.",
    "aqua-gucci": "Grey laid in fine directional layers, folded and banded across the slab.",
    "marron-imperial": "A deep brown with pale cream flecks and fine lighter veining.",
    "verde-alpi": "A dark green, close to black, cut through with white and pale green veining.",
    "calacatta-brasil": "White with grey veining in loose connected runs.",
    "macaubas-fantasy": "White with pale green and grey banding running in one direction.",
    "calacatta-cremo-honed": "A warm white with soft grey veining running diagonally, matt rather than glossy.",
    "mont-blanc": "A very pale white with fine grey veining running in soft horizontal lines.",
    "calacatta-viola-honed": "White with dramatic purple and charcoal veining, matt rather than glossy.",
    "nero-marinace": "Rounded grey and cream pebbles set in a dark matrix, a conglomerate rather than a veined stone.",
    "cote-d-azur": "A vivid blue and teal surface with warm brown and orange running through it.",
    "fusion-wow-multicolour": "Orange, salmon and grey in flowing folded layers across the slab.",
    "mystic-grey": "A mid grey with darker mottling and faint pale veining.",
    "arabescato-corchia-extra": "White rounded shapes set in a grey violet matrix.",
    "white-macaubas": "White with fine grey green striations running horizontally.",
    "ocean-fantasy": "Blue, grey and tan laid in flowing folded layers.",
    "carrara": "White with a fine grey feathering scattered evenly across it.",
    "rosa-alicante": "A deep pink red with white veining crossing it in fine branching lines.",
    "magma-gold": "Copper orange and black in flowing folded bands.",
    "belvedere": "Black with gold striations in horizontal layers, polished to a gloss.",
    "dover-white": "White and pale lilac shapes framed by dark grey veining.",
    "rosso-levanto": "A deep red brown with white and pale green veining in a dense network.",
    "cosmic-black": "Black with grey and white veining flowing across it in soft folds.",
    "blue-roma-honed": "A pale blue grey with brown gold veining in sharp angular lines, matt rather than glossy.",
    "dolce-vita": "A soft white with grey green and warm brown veining drifting across it.",

    # ---------------------------------------------------------------- GRANITE
    "absolute-black-extra": "A solid black with no pattern in it, polished to a deep gloss.",
    "antiq-brown-extra": "A very dark brown, close to black, with a fine speckle through it.",
    "azul-platino": "A mid grey with a fine even speckle of pale and dark grain.",
    "astoria": "A warm cream with peach and pale grey flowing softly across it.",
    "bianco-crystal": "A pale grey with a fine scatter of dark specks and no veining.",
    "blue-dunes-leather": "Cream, grey and tan in layered horizontal bands, textured rather than glossy.",
    "colonial-cream": "A cream grey with a dense fine speckle and small dark flecks through it.",
    "colombo-juparana": "Cream and pink swirling with grey and green in flowing folded bands.",
    "baltic-brown": "Large rounded brown crystals set in a darker olive and black matrix.",
    "bianco-sardo": "A white and grey granite with a dense even speckle of black and white grain.",
    "blue-pearl": "A dark blue grey with a fine iridescent flecking that catches the light.",
    "arctic-cream": "A cream white with grey green mottling and fine dark veining.",
    "blues-in-the-night": "A very dark blue grey, near plain, with a faint sparkle in the surface.",
    "antiq-brown-leather": "A very dark brown with a mottled grain, textured rather than glossy.",
    "angola-black-leather": "A dark grey black with a fine even grain, textured rather than glossy.",
    "absolute-black-brushed": "A plain black granite brushed to a low sheen, reading as a soft dark grey.",
    "black-pearl": "A dark near black with fine pale flecks scattered through it.",
    "absolute-black-leather": "A plain black granite finished leathered, reading as a deep charcoal with a texture you can feel.",
    "absolute-black-honed": "A plain black granite finished honed, reading as a deep charcoal rather than a gloss black.",
    "bianco-antico": "White and grey with dark green and black mottling scattered across it.",

    # ---- the dark quartz, added 10 Aug 2026 (catalogue_dark.py) -------------------------
    # ⚠️ Each of these was written with its tile open at 330px. Colour and pattern only.
    "vanilla-noir": "A near black ground broken up by a dense web of cream and gold marbling.",
    "black-tempal": "A soft near black with a fine even grain and no veining through it.",
    "woodlands": "A dark chocolate brown with copper and gold mottling spread across it.",
    # ⭐ THE MIRROR RANGE (11 Aug). Written with each 1600px tile open, colour and pattern only.
    # ⚠️ These are mirror-fleck quartz: the chips ARE the pattern, so that is what the line says.
    "white-mirror": "A bright white packed with broken mirror chips, the flecks large enough to "
                    "read as pieces rather than glitter.",
    "cream-mirror": "A soft cream ground with fine dark speckle and mirror flecks scattered "
                    "evenly through it.",
    "grey-mirror": "A mid grey with dense dark speckle, lit by mirror flecks that catch the light "
                   "across the surface.",
    "brown-mirror": "A dark chocolate brown, finely speckled, with mirror flecks picked out "
                    "against it.",
    "blue-mirror": "A deep navy scattered with bright mirror flecks, the ground dark enough to "
                   "make them read like points of light.",
    "black-mirror": "A black ground carrying bright mirror flecks, spaced wide so each one "
                    "catches the light on its own.",
    "darcrest": "A dark slate with paler grey clouding drifting through it in broad bands.",
    "marquina": "A deep blue black cut by fine white veins that fork across the surface.",
    "laurent-black": "A black ground with warm gold veins running through it in long diagonals.",
    "azalai-negro": "A black ground with fine white and gold veins crossing it in straight lines.",
    "umbra-marron": "A dark brown ground with grey and white flecking scattered right across it.",
    "cristallo-gris": "A mid to dark grey with white veining running diagonally across it.",
    "labradorite-royal": "A deep teal blue with gold and rust markings breaking across the surface.",
    "nero-starlight": "A near black with fine pale sparkle scattered evenly through it.",
}
