/* GENERATED by scripts/extract-home-data.mjs from assets/site.js:2539 — FAQS. Do not hand-edit. */

/**
 * Twelve questions in four groups. The index down the left renders `label`
 * (the short form) with `q` behind it for the selected state; the plate shows
 * `tag`, `q` and `a`. Group order is the array's own order — the builder
 * starts a new group whenever `g` changes, so the array must stay sorted by
 * group, and it is.
 */
export interface Faq {
  /** Group heading in the index. */
  g: string;
  /** Short label in the index. */
  label: string;
  /** Eyebrow above the question in the plate. */
  tag: string;
  q: string;
  a: string;
}

export const FAQS: readonly Faq[] = [
  {
    "g": "Price and guarantee",
    "label": "What it costs",
    "tag": "Pricing",
    "q": "How much does a stone worktop cost?",
    "a": "It depends on the stone, the size of your kitchen and the detailing, but most kitchens fall within a clear range, which the estimator above shows you in seconds. Your exact, itemised price, covering template, fabrication, fitting and VAT, follows a free home visit, with nothing hidden."
  },
  {
    "g": "Price and guarantee",
    "label": "Hidden costs",
    "tag": "Pricing",
    "q": "Are there any hidden costs?",
    "a": "None. Your quote covers templating, precision cutting and installation, itemised in full before any work begins. Cut-outs, drainer grooves and pencil edges come as standard rather than as extras. The price we agree is the price you pay."
  },
  {
    "g": "Price and guarantee",
    "label": "Our guarantee",
    "tag": "Aftercare",
    "q": "What happens if something is not right after fitting?",
    "a": "We come back and put it right, free of charge. Every kitchen is made by hand, so now and again a surface wants a small adjustment once you have lived with it for a few days. The difference is how long you wait. We have never taken more than 72 hours to come back out, and the ten year guarantee sits behind the work either way."
  },
  {
    "g": "How it works",
    "label": "How long it takes",
    "tag": "Process",
    "q": "How long does it take, start to finish?",
    "a": "From template to fitted worktop is typically three to five working days. One visit to template your kitchen by hand to the millimetre, then our fitters install the finished surface, and we are back inside 72 hours if anything at all needs attention."
  },
  {
    "g": "How it works",
    "label": "Who comes to your home",
    "tag": "Process",
    "q": "Who will actually be coming to my home?",
    "a": "The same small team throughout. One of us comes out to template, and the same team fits it. The cutting is done by our own experienced fabricators, so the whole job stays with us rather than being passed down the line. You get one name and one number for the whole job, so you always know who is coming and when."
  },
  {
    "g": "How it works",
    "label": "Where we work",
    "tag": "Areas",
    "q": "Which areas do you cover?",
    "a": "London, Hertfordshire, Essex, Berkshire, Buckinghamshire, Surrey, Oxfordshire and Bedfordshire for the full service, and we template nationwide for projects worth the journey. If you are just outside these areas, ask. We are always happy to see if we can help."
  },
  {
    "g": "Your stone",
    "label": "Choosing your stone",
    "tag": "Materials",
    "q": "Quartz, granite or marble, which is right for me?",
    "a": "There is no single best, it depends on how you live. Quartz suits most busy kitchens: durable, non-porous, no sealing. Granite is natural, heat-tolerant and hard-wearing. Marble is the most beautiful but needs care, as it etches and patinas. Tell us how you cook and we will steer you honestly."
  },
  {
    "g": "Your stone",
    "label": "Matching your slab",
    "tag": "Materials",
    "q": "Will the slab match the sample I saw?",
    "a": "Natural stone varies, that is its beauty. Before a single cut is made you approve your exact slab from photographs of the piece itself, so the veining you fall for is precisely what arrives in your kitchen. You are also welcome to visit the distributor's warehouse and choose your slab in person, which for natural stone we highly recommend."
  },
  {
    "g": "Your stone",
    "label": "Porcelain and sintered",
    "tag": "Materials",
    "q": "Do you work with porcelain and sintered stone?",
    "a": "Yes, made to order. Porcelain takes direct heat, holds its colour in sunlight and works outdoors as well as in, which is why it suits outdoor kitchens and the run beside a hob. It is cut on a waterjet rather than a saw and the thin edges are mitred by hand to read as solid stone, so we price it against your plans rather than from a calculator. Send us what you have and we will come back with a figure."
  },
  {
    "g": "Living with it",
    "label": "Seams and joints",
    "tag": "Craftsmanship",
    "q": "Will I be able to see the seams?",
    "a": "A seam is always visible, and anyone who tells you otherwise is selling you something. What we can do is place it where it is least in the way, close it tight and match the veining through it, so it reads as part of the stone rather than as a join. We will show you where every seam will fall before anything is cut."
  },
  {
    "g": "Living with it",
    "label": "Hot pans and heat",
    "tag": "Care",
    "q": "Can I put a hot pan straight onto it?",
    "a": "On granite and porcelain, yes. Quartz is the one to be careful with, because the resin that binds it can mark if a pan comes straight off the hob, so use a trivet. If you cook hard and would rather never think about it, porcelain takes direct heat without complaint, and plenty of kitchens run porcelain around the hob and quartz everywhere else."
  },
  {
    "g": "Living with it",
    "label": "Silica and safety",
    "tag": "Safety",
    "q": "Is a stone worktop safe to have in the house?",
    "a": "Completely. A sealed, installed worktop poses no silica risk in your home, the dust risk comes from the fabrication process and not from having a finished worktop in your kitchen. It matters all the same, which is why we carry out our fabrication in our own workshop, where we control the cutting process, use appropriate dust extraction and wet-cutting methods, and follow current HSE guidance."
  }
];

/** site.js:2606 — a new group starts wherever `g` changes, never re-sorted. */
export function faqGroups(items: readonly Faq[] = FAQS): { name: string; items: number[] }[] {
  const groups: { name: string; items: number[] }[] = [];
  items.forEach((f, i) => {
    let g = groups[groups.length - 1];
    if (!g || g.name !== f.g) {
      g = { name: f.g, items: [] };
      groups.push(g);
    }
    g.items.push(i);
  });
  return groups;
}
