/* GENERATED by scripts/extract-home-data.mjs from assets/site.js:1443 — REVIEWS. Do not hand-edit. */

/**
 * Google reviews, verbatim, including the emoji and the curly quotes.
 *
 * The source array ends with `.filter(r => !/luke|copley|thadeus|tabrez/i
 * .test(r.n))` — four reviewers the client asked to be withheld. That filter
 * is applied at extraction time, so this array is exactly what renders.
 */
export interface Review {
  /** Reviewer name as shown. */
  n: string;
  /** The review body. Rendered inside typographic quotes by the card. */
  q: string;
}

export const REVIEWS: readonly Review[] = [
  {
    "n": "Judy Z.",
    "q": "10/10 experience!! I had Nick as my point of contact for the end to end stone worktop work, it was extremely smooth process with minimal hustle. From the beginning, Nick was very professional, responsive and polite, which was a great customer experience for me. The team came in the next week to measure and Nick ordered the stone right away, so it was ready for installation 3-4 days after they templated the worktop. On the installation day, the team spent about 1.5h to complete the work and has done a clean job. The 2 workers on the day were absolutely brilliant, and have done a great service! 🙏 Basically, there was a window corner which was not originally planned to install any 10cm stone cover, but they brought the extra materials and cut the bit of window frame perfectly and installed it on the day (as I was there in person and they checked with me before making any adjustments). Very happy with my experience"
  },
  {
    "n": "Jhanzeb Chaudhry",
    "q": "I’m so happy I went with Topcat Worktops for my kitchen! I had visited a few kitchen showrooms before and was honestly shocked at how expensive the quotes were. Topcat came in at least £1,200 cheaper than the others, and the quality and service were absolutely amazing. Nik was brilliant from the start, super helpful, always available to answer my questions (even out of hours), and guided me through the whole process with real care. On installation day, the team arrived on time and did a fantastic job. The finish is flawless, and everything was done to a really high standard. Highly recommend Topcat Worktops, great prices, great service, and a beautiful end result!"
  },
  {
    "n": "Maheen Amjad",
    "q": "Topcat Worktops came highly recommended by our interior designer, and they certainly didn't disappoint. As we're based in Scotland, everything was handled over the phone and email, but Nick made the whole process incredibly easy. He was always quick to respond, answered all our questions, and helped us choose the right worktop for our kitchen without any pressure. The service was professional from start to finish, and we always felt well looked after despite being hundreds of miles away. The Topcat Worktops team installed the worktop and the quality is excellent. We're delighted with the finished result and wouldn't hesitate to recommend Topcat Worktops to others."
  },
  {
    "n": "Cherif",
    "q": "Excellent service, quick responses and my Quartz kitchen worktop was installed within 48 hours from my initial conversation with Nick"
  },
  {
    "n": "Joel Brizman",
    "q": "Highly recommended: Topcat Worktops replaced our old kitchen worktop with a new quartz worktop. The process was quick and seamless. From the initial visit, their friendly staff took care to understand our vision and our requirements, which included a one-source A-to-Z solution (including removal and disposal of the old worktop and a complete refit of our existing plumbing and electric hob). The installation was carried out very quickly after ordering - and was smooth, efficient with the installers taking great care to ensure there was no damage to surroundings. We are very satisfied with the process and the outcome."
  },
  {
    "n": "Abbas",
    "q": "We recently chose a Calacatta Viola worktop from Topcat Worktops Ltd and couldn't be happier with the result. The team were helpful throughout the whole process and made everything easy from start to finish. The installation was carried out professionally and the worktop looks absolutely stunning in our kitchen. Would definitely recommend Topcat Worktops to anyone looking for quality products and excellent service."
  },
  {
    "n": "Maria Shahsawar",
    "q": "Really pleased with our new kitchen worktops from Topcat Worktops. Nick was brilliant from start to finish, very responsive, patient while we decided on colours and materials, and provided a free no-obligation quote with no pressure at all. The quality of the worktops and installation is excellent, and the finished kitchen looks amazing. The team were professional, tidy, and completed everything to a high standard. Would definitely recommend Topcat Worktops to anyone looking for new kitchen worktops."
  },
  {
    "n": "Davinder Dhillon",
    "q": "I’ve just had my quartz worktop installed, and I’m already thrilled with how it looks and feels. The finish is smooth, modern, and really elevates the whole kitchen. The craftsmanship is excellent, clean edges, seamless joints, and a perfect fit around the sink and hob. Even though it’s brand new, I can already tell it’s going to be easy to maintain and very durable. Overall, I’m extremely happy with the installation and excited to start using it."
  },
  {
    "n": "Kav Patel",
    "q": "Very pleased with the service that was provided by Topcats . Whilst our project took longer than expected, Topcats were very patient with us and delivered amazing worktops to complement our kitchen. Would definitely recommend Topcats and a big shout out to Nick who we started the journey with back in Feb 2025."
  },
  {
    "n": "Kinga Skubiszewska",
    "q": "Excellent experience from start to finish. Professional, responsive, and easy to work with throughout the project. Communication was clear, the work was completed to a high standard, and the entire process was handled efficiently. I am very happy with the results and would gladly work with them again. Highly recommended."
  },
  {
    "n": "Ali Jaffer",
    "q": "Really happy with their work. Nick was really helpful and transparent about the whole process, easy comms and a flawless finish. Would definitely recommend!"
  },
  {
    "n": "Naied Khan",
    "q": "Had kitchen work tops and back splash done. Work was done professionally with special attention to details. Everything was done within the time frame, and I am very happy with the results and the suggestions that were recommended, great service, and highly professional. Highly recommend 👌"
  },
  {
    "n": "Farah Remadna",
    "q": "Excellent service from start to finish. Everything was completed perfectly with great attention to detail. The team was friendly, professional, and easy to work with. Highly recommended!"
  },
  {
    "n": "Megan Webb",
    "q": "Excellent service and a wonderful company to work with - I would recommend to anyone."
  },
  {
    "n": "Han L.",
    "q": "Splashback was phenomenal, quick responses, reasonable pricing. Would recommend."
  }
];
