/* GENERATED by scripts/extract-home-data.mjs from assets/site.js:113 — SERVICES. Do not hand-edit. */

/**
 * The eight cards in the services strip, in source order. `long` is the copy
 * on the back of the flip card; the front shows only the title, because the
 * home page calls buildCards with `nameOnly` (site.js) and so never renders
 * the `d` field that other pages use.
 */
export interface Service {
  /** Card title, also the flip-card's accessible name. */
  t: string;
  /** Back-of-card paragraph. */
  long: string;
  /** Legacy .html leaf under /services/. */
  href: string;
  /** Display URL; look it up in SRCSET for the responsive set. */
  img: string;
}

export const SERVICES: readonly Service[] = [
  {
    "t": "Kitchen Worktops",
    "long": "Worktops cut from a single slab where the run allows, islands with mitred waterfall ends that fold the stone to the floor, templated to the millimetre and fitted by our own team.",
    "href": "/services/kitchen-worktops.html",
    "img": "/assets/site/service-worktops-quartz-2400.webp"
  },
  {
    "t": "Splashbacks",
    "long": "The same stone carried up the wall, cut around sockets and hobs, with no grout lines and no visual break above the worktop.",
    "href": "/services/splashbacks.html",
    "img": "/assets/site/service-splash-hob-1200.webp"
  },
  {
    "t": "Bathrooms",
    "long": "Shower surrounds, thresholds and window sills cut from one stone, so the room reads as a single material rather than a set of parts.",
    "href": "/services/bathroom-worktops.html",
    "img": "/assets/site/service-bathrooms-2400.webp"
  },
  {
    "t": "Outdoor Spaces",
    "long": "Weatherproof stone for garden kitchens, barbecue runs and outdoor bars, cut to fit around sinks, hobs and built-in appliances.",
    "href": "/services/outdoor-kitchens.html",
    "img": "/assets/site/service-outdoor-2400.webp"
  },
  {
    "t": "Fireplaces",
    "long": "Hearths, surrounds and mantels cut to your opening and finished by hand, in the same stone as the rest of the house if you want the rooms to tie together.",
    "href": "/services/fireplaces.html",
    "img": "/assets/site/service-fireplaces-1550.webp"
  },
  {
    "t": "Dining Tables",
    "long": "Table and console tops cut to your shape and edge profile, in the same stone as the kitchen, so the piece reads as part of the room rather than as furniture bought separately.",
    "href": "/services/dining-tables.html",
    "img": "/assets/site/service-dining-2400.webp"
  },
  {
    "t": "Vanity Tops",
    "long": "Basin tops cut for undermount or countertop basins, with the tap holes exactly where you want them and the edges finished to match.",
    "href": "/services/vanity-tops.html",
    "img": "/assets/site/service-vanity-2400.webp"
  },
  {
    "t": "Commercial",
    "long": "Reception desks, counters and washroom surfaces for offices, bars and shops, fitted to your programme by one team.",
    "href": "/services/commercial-worktops.html",
    "img": "/assets/site/service-commercial-bar-2400.webp"
  }
];
